sweeft_workout/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from sweeft_workout import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sweeft-sport/', include('users.urls')),
    path('sweeft-sport/', include('trainings.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

trainings/urls.py
from django.urls import path
from trainings import views

app_name = 'trainings'

urlpatterns = [
    path('trainings/', views.IndexView.as_view(), name='index')
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from users import views




app_name = 'users'

urlpatterns = [
    path('profile/', views.profile, name='profile'),
    path('registration/', views.UserRegistrationView.as_view(), name='registration'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

trainings/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    image = models.ImageField(upload_to='user_avatars', null=True, blank=True)

users/forms.py
from django.contrib.auth.forms import AuthenticationForm,  UserCreationForm
from django import forms

from users.models import User


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'required': True}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'required': True}))


class UserRegistrationForm(UserCreationForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'required': True}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'required': True}))
    username = forms.CharField(widget=forms.TextInput(attrs={'required': True}))
    email = forms.CharField(widget=forms.EmailInput(attrs={'required': True}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'required': True}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'required': True}))

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2']

common/views.py
class TitleMixin:
    title = None

    def get_context_data(self, **kwargs):
        context = super(TitleMixin, self).get_context_data(**kwargs)
        context['title'] = self.title
        return context
    

trainings/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from common.views import TitleMixin


class IndexView(TitleMixin, TemplateView):
    template_name = 'workout/index.html'
    title = 'Sweeft-Sport'

users/views.py
from django.shortcuts import render
from django.contrib.auth.views import LoginView
from django.views.generic import ListView
from django.urls import reverse, reverse_lazy
from django.views.generic.edit import CreateView

from common.views import TitleMixin
from users.forms import UserLoginForm, UserRegistrationForm
from users.models import User


class UserLoginView(TitleMixin, LoginView):
    template_name = 'users/login.html'
    form_class = UserLoginForm
    title = 'Login'
   

class UserRegistrationView(TitleMixin, CreateView):
    model = User
    form_class = UserRegistrationForm
    template_name = 'users/registration.html'
    success_url = reverse_lazy('users:login')
    title = 'Registration'



def profile(request):
    return render(request, 'users/profile.html')

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

    <title>{% block title %}{% endblock %} </title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">


    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/templatemo-cyborg-gaming.css' %} ">
    <link rel="stylesheet" href="{% static 'assets/css/owl.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/animate.css' %}">
    <link rel="stylesheet"href="https://unpkg.com/swiper@7/swiper-bundle.min.css"/>
<!--

TemplateMo 579 Cyborg Gaming

https://templatemo.com/tm-579-cyborg-gaming

-->
  </head>

<body>

  <!-- ***** Preloader Start ***** -->
  <div id="js-preloader" class="js-preloader">
    <div class="preloader-inner">
      <span class="dot"></span>
      <div class="dots">
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>
  </div>
  <!-- ***** Preloader End ***** -->

  <!-- ***** Header Area Start ***** -->
  <header class="header-area header-sticky">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <nav class="main-nav">
                    <!-- ***** Logo Start ***** -->
                    <a href="index.html" class="logo">
                        <img src="{% static 'images/m.png'%}" alt="">
                    </a>
                    <!-- ***** Logo End ***** -->

                    <!-- ***** Menu Start ***** -->
                    <ul class="nav">
                        <li><a href="index.html" class="active">Home</a></li>
                        <li><a href="{% url 'users:registration' %}" class="active">Registration</a></li>
                        {% if user.is_authenticated %}
                            <li><a href="{% url 'users:logout' %}" class="active" >Logout</a></li>
                            <li><a href="{% url 'users:profile' %}">Profile <img src="
                              {% if user.image %}
                                {{ user.image.url }}
                              {% else %}  
                                {% static 'images/no_img.png' %}
                              {% endif %}" alt=""></a></li>
                        {% else %}
                            <li><a href="{% url 'users:login' %}" class="active">Login</a></li>
                        {% endif %}
                    </ul>   
                    <a class='menu-trigger'>
                        <span>Menu</span>
                    </a>
                    <!-- ***** Menu End ***** -->
                </nav>
            </div>
        </div>
    </div>
  </header>
  <!-- ***** Header Area End ***** -->

  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="page-content">


          {% block content %} {% endblock %}
          
  
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <p>Copyright © 2036 <a href="#">Cyborg Gaming</a> Company. All rights reserved. 
          
          <br>Design: <a href="https://templatemo.com" target="_blank" title="free CSS templates">TemplateMo</a></p>
        </div>
      </div>
    </div>
  </footer>


  <!-- Scripts -->
  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>

  <script src="{% static 'assets/js/isotope.min.js' %}"></script>
  <script src="{% static 'assets/js/owl-carousel.js' %}"></script>
  <script src="{% static 'assets/js/tabs.js' %}"></script>
  <script src="{% static 'assets/js/popup.js' %}"></script>
  <script src="{% static 'assets/js/custom.js' %}"></script>


  </body>

</html>

templates/users/login.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>{% block title %}{{ title }}{% endblock %}</title>
	<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
	<link href="http://infiniteiotdevices.com/images/logo.png" rel="icon" sizes="16x16" type="image/gif" />
	<link rel="stylesheet" type="text/css" href="{% static 'login/CSS/login-form-5.css' %}">
</head>
<body>
	<div class="box">
		<h2>Login</h2>
		<form action="{% url 'users:login' %}" method="post">
			{% csrf_token %}
			<div class="inputBox">
				{{ form.username }}
				<label>{{ form.username.label }}</label>
			</div>
			<div class="inputBox">
				{{ form.password }}
				<label>{{ form.password.label }}</label>
			</div>
			<input type="submit" name="" value="submit">
		</form>
		<h5>Sign Up Using</h5>
		<ul>
			<li>
			<a href="#">
				<span></span>
				<span></span>
				<span></span>
				<span></span>
				<i class="fa fa-facebook"></i>
			</a>
		</li>
		<li>
			<a href="#">
				<span></span>
				<span></span>
				<span></span>
				<span></span>
				<i class="fa fa-google"></i>
			</a>
		</li>
		</ul>
		<h4>Create account? <a href="#">Sign Up</a></h4>
	</div>
</body>
</html>

templates/users/profile.html
{% extends 'base.html '%}
{% load static %}


{% block content %}
    <!-- ***** Banner Start ***** -->
        <div class="row">
        <div class="col-lg-12">
            <div class="main-profile ">
            <div class="row">
                <div class="col-lg-4">
                <img src="{% static 'assets/images/profile.jpg' %}" alt="" style="border-radius: 23px;">
                </div>
                <div class="col-lg-4 align-self-center">
                <div class="main-info header-text">
                    <span>Offline</span>
                    <h4>Alan Smithee</h4>
                    <p>You Haven't Gone Live yet. Go Live By Touching The Button Below.</p>
                    <div class="main-border-button">
                    <a href="#">Start Live Stream</a>
                    </div>
                </div>
                </div>
                <div class="col-lg-4 align-self-center">
                <ul>
                    <li>Games Downloaded <span>3</span></li>
                    <li>Friends Online <span>16</span></li>
                    <li>Live Streams <span>None</span></li>
                    <li>Clips <span>29</span></li>
                </ul>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                <div class="clips">
                    <div class="row">
                    <div class="col-lg-12">
                        <div class="heading-section">
                        <h4><em>Your Most Popular</em> Clips</h4>
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-6">
                        <div class="item">
                        <div class="thumb">
                            <img src="{% static 'assets/images/clip-01.jpg' %}" alt="" style="border-radius: 23px;">
                            <a href="https://www.youtube.com/watch?v=r1b03uKWk_M" target="_blank"><i class="fa fa-play"></i></a>
                        </div>
                        <div class="down-content">
                            <h4>First Clip</h4>
                            <span><i class="fa fa-eye"></i> 250</span>
                        </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-6">
                        <div class="item">
                        <div class="thumb">
                            <img src="{% static 'assets/images/clip-02.jpg' %}" alt="" style="border-radius: 23px;">
                            <a href="https://www.youtube.com/watch?v=r1b03uKWk_M" target="_blank"><i class="fa fa-play"></i></a>
                        </div>
                        <div class="down-content">
                            <h4>Second Clip</h4>
                            <span><i class="fa fa-eye"></i> 183</span>
                        </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-6">
                        <div class="item">
                        <div class="thumb">
                            <img src="{% static 'assets/images/clip-03.jpg' %}" alt="" style="border-radius: 23px;">
                            <a href="https://www.youtube.com/watch?v=r1b03uKWk_M" target="_blank"><i class="fa fa-play"></i></a>
                        </div>
                        <div class="down-content">
                            <h4>Third Clip</h4>
                            <span><i class="fa fa-eye"></i> 141</span>
                        </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-6">
                        <div class="item">
                        <div class="thumb">
                            <img src="{% static 'assets/images/clip-04.jpg' %}" alt="" style="border-radius: 23px;">
                            <a href="https://www.youtube.com/watch?v=r1b03uKWk_M" target="_blank"><i class="fa fa-play"></i></a>
                        </div>
                        <div class="down-content">
                            <h4>Fourth Clip</h4>
                            <span><i class="fa fa-eye"></i> 91</span>
                        </div>
                        </div>
                    </div>
                    <div class="col-lg-12">
                        <div class="main-button">
                        <a href="#">Load More Clips</a>
                        </div>
                    </div>
                    </div>
                </div>
                </div>
            </div>
            </div>
        </div>
        </div>
        <!-- ***** Banner End ***** -->

        <!-- ***** Gaming Library Start ***** -->
        <div class="gaming-library profile-library">
        <div class="col-lg-12">
            <div class="heading-section">
            <h4><em>Your Gaming</em> Library</h4>
            </div>
            <div class="item">
            <ul>
                <li><img src="{% static 'assets/images/game-01.jpg' %}" alt="" class="templatemo-item"></li>
                <li><h4>Dota 2</h4><span>Sandbox</span></li>
                <li><h4>Date Added</h4><span>24/08/2036</span></li>
                <li><h4>Hours Played</h4><span>634 H 22 Mins</span></li>
                <li><h4>Currently</h4><span>Downloaded</span></li>
                <li><div class="main-border-button border-no-active"><a href="#">Donwloaded</a></div></li>
            </ul>
            </div>
            <div class="item">
            <ul>
                <li><img src="{% static 'assets/images/game-02.jpg' %}" alt="" class="templatemo-item"></li>
                <li><h4>Fortnite</h4><span>Sandbox</span></li>
                <li><h4>Date Added</h4><span>22/06/2036</span></li>
                <li><h4>Hours Played</h4><span>745 H 22 Mins</span></li>
                <li><h4>Currently</h4><span>Downloaded</span></li>
                <li><div class="main-border-button border-no-active"><a href="#">Donwloaded</a></div></li>
            </ul>
            </div>
            <div class="item last-item">
            <ul>
                <li><img src="{% static 'assets/images/game-03.jpg' %}" alt="" class="templatemo-item"></li>
                <li><h4>CS-GO</h4><span>Sandbox</span></li>
                <li><h4>Date Added</h4><span>21/04/2022</span></li>
                <li><h4>Hours Played</h4><span>632 H 46 Mins</span></li>
                <li><h4>Currently</h4><span>Downloaded</span></li>
                <li><div class="main-border-button border-no-active"><a href="#">Donwloaded</a></div></li>
            </ul>
            </div>
        </div>
        </div>
        <!-- ***** Gaming Library End ***** -->
    </div>
    </div>
</div>
</div>
{% endblock %}

templates/users/registration.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>{% block title %}{{ title }}{% endblock %}</title>
	<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
	<link href="http://infiniteiotdevices.com/images/logo.png" rel="icon" sizes="16x16" type="image/gif" />
	<link rel="stylesheet" type="text/css" href="{% static 'assets/CSS/registration.css' %}">
</head>
<body>
	<div class="box">
		<h2>Create account</h2>
		<form action="{% url 'users:registration' %}" method="post">
            {% csrf_token %}
			<div class="inputBox">
				{{ form.first_name }}
				<label>{{ form.first_name.label }}</label>
			</div>
			<div class="inputBox">
				{{ form.last_name }}
				<label>{{ form.last_name.label }}</label>
			</div>
            <div class="inputBox">
				{{ form.username }}
				<label>{{ form.username.label }}</label>
			</div>
            <div class="inputBox">
				{{ form.email }}
				<label>{{ form.email.label }}</label>
			</div>
            <div class="inputBox">
				{{ form.password1 }}
				<label>{{ form.password1.label }}</label>
			</div>
            <div class="inputBox">
				{{ form.password2 }}
				<label>{{ from.password2.label }}Confim Password</label>
			</div>
			<input type="submit" name="" value="submit">
		</form>
		<h4>Already have an account? <a href="#">Login</a></h4>
	</div>
</body>
</html>

templates/workout/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <!-- ***** Banner Start ***** -->
    <div class="main-banner">
        <div class="row">
        <div class="col-lg-7">
            <div class="header-text">
            <h6>Welcome To Cyborg</h6>
            <h4><em>Browse</em> Our Popular Games Here</h4>
            <div class="main-button">
                <a href="browse.html">Browse Now</a>
            </div>
            </div>
        </div>
        </div>
    </div>
    <!-- ***** Banner End ***** -->

    <!-- ***** Most Popular Start ***** -->
    <div class="most-popular">
        <div class="row">
        <div class="col-lg-12">
            <div class="heading-section">
            <h4><em>Most Popular</em> Right Now</h4>
            </div>
            <div class="row">
            <div class="col-lg-3 col-sm-6">
                <div class="item">
                <img src="{% static 'assets/images/popular-01.jpg' %}" alt="">
                <h4>Fortnite<br><span>Sandbox</span></h4>
                <ul>
                    <li><i class="fa fa-star"></i> 4.8</li>
                    <li><i class="fa fa-download"></i> 2.3M</li>
                </ul>
                </div>
            </div>
            <div class="col-lg-3 col-sm-6">
                <div class="item">
                <img src="{% static 'assets/images/popular-02.jpg' %}" alt="">
                <h4>PubG<br><span>Battle S</span></h4>
                <ul>
                    <li><i class="fa fa-star"></i> 4.8</li>
                    <li><i class="fa fa-download"></i> 2.3M</li>
                </ul>
                </div>
            </div>
            <div class="col-lg-3 col-sm-6">
                <div class="item">
                <img src="{% static 'assets/images/popular-03.jpg' %}" alt="">
                <h4>Dota2<br><span>Steam-X</span></h4>
                <ul>
                    <li><i class="fa fa-star"></i> 4.8</li>
                    <li><i class="fa fa-download"></i> 2.3M</li>
                </ul>
                </div>
            </div>
            <div class="col-lg-3 col-sm-6">
                <div class="item">
                <img src="{% static 'assets/images/popular-04.jpg' %}" alt="">
                <h4>CS-GO<br><span>Legendary</span></h4>
                <ul>
                    <li><i class="fa fa-star"></i> 4.8</li>
                    <li><i class="fa fa-download"></i> 2.3M</li>
                </ul>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="item">
                <div class="row">
                    <div class="col-lg-6 col-sm-6">
                    <div class="item inner-item">
                        <img src="{% static 'assets/images/popular-05.jpg' %}" alt="">
                        <h4>Mini Craft<br><span>Legendary</span></h4>
                        <ul>
                        <li><i class="fa fa-star"></i> 4.8</li>
                        <li><i class="fa fa-download"></i> 2.3M</li>
                        </ul>
                    </div>
                    </div>
                    <div class="col-lg-6 col-sm-6">
                    <div class="item">
                        <img src="{% static 'assets/images/popular-06.jpg' %}" alt="">
                        <h4>Eagles Fly<br><span>Matrix Games</span></h4>
                        <ul>
                        <li><i class="fa fa-star"></i> 4.8</li>
                        <li><i class="fa fa-download"></i> 2.3M</li>
                        </ul>
                    </div>
                    </div>
                </div>
                </div>
            </div>
            <div class="col-lg-3 col-sm-6">
                <div class="item">
                <img src="{% static 'assets/images/popular-07.jpg' %}" alt="">
                <h4>Warface<br><span>Max 3D</span></h4>
                <ul>
                    <li><i class="fa fa-star"></i> 4.8</li>
                    <li><i class="fa fa-download"></i> 2.3M</li>
                </ul>
                </div>
            </div>
            <div class="col-lg-3 col-sm-6">
                <div class="item">
                <img src="{% static 'assets/images/popular-08.jpg' %}" alt="">
                <h4>Warcraft<br><span>Legend</span></h4>
                <ul>
                    <li><i class="fa fa-star"></i> 4.8</li>
                    <li><i class="fa fa-download"></i> 2.3M</li>
                </ul>
                </div>
            </div>
            <div class="col-lg-12">
                <div class="main-button">
                <a href="browse.html">Discover Popular</a>
                </div>
            </div>
            </div>
        </div>
        </div>
    </div>
    <!-- ***** Most Popular End ***** -->

    <!-- ***** Gaming Library Start ***** -->
    <div class="gaming-library">
        <div class="col-lg-12">
        <div class="heading-section">
            <h4><em>Your Gaming</em> Library</h4>
        </div>
        <div class="item">
            <ul>
            <li><img src="{% static 'assets/images/game-01.jpg' %}" alt="" class="templatemo-item"></li>
            <li><h4>Dota 2</h4><span>Sandbox</span></li>
            <li><h4>Date Added</h4><span>24/08/2036</span></li>
            <li><h4>Hours Played</h4><span>634 H 22 Mins</span></li>
            <li><h4>Currently</h4><span>Downloaded</span></li>
            <li><div class="main-border-button border-no-active"><a href="#">Donwloaded</a></div></li>
            </ul>
        </div>
        <div class="item">
            <ul>
            <li><img src="{% static 'assets/images/game-02.jpg' %}" alt="" class="templatemo-item"></li>
            <li><h4>Fortnite</h4><span>Sandbox</span></li>
            <li><h4>Date Added</h4><span>22/06/2036</span></li>
            <li><h4>Hours Played</h4><span>740 H 52 Mins</span></li>
            <li><h4>Currently</h4><span>Downloaded</span></li>
            <li><div class="main-border-button"><a href="#">Donwload</a></div></li>
            </ul>
        </div>
        <div class="item last-item">
            <ul>
            <li><img src="{% static 'assets/images/game-03.jpg' %}" alt="" class="templatemo-item"></li>
            <li><h4>CS-GO</h4><span>Sandbox</span></li>
            <li><h4>Date Added</h4><span>21/04/2036</span></li>
            <li><h4>Hours Played</h4><span>892 H 14 Mins</span></li>
            <li><h4>Currently</h4><span>Downloaded</span></li>
            <li><div class="main-border-button border-no-active"><a href="#">Donwloaded</a></div></li>
            </ul>
        </div>
        </div>
        <div class="col-lg-12">
        <div class="main-button">
            <a href="profile.html">View Your Library</a>
        </div>
        </div>
    </div>
    <!-- ***** Gaming Library End ***** -->
    </div>
    </div>
    </div>
    </div>
{% endblock %}